const mongoose = require('mongoose');
const { Schema } = mongoose;

const hintSchema = new Schema(
  {
    text: {
      type: String,
      required: true,
    },
    penaltySeconds: {
      type: Number,
      required: true,
      default: 30,
      min: 0,
    },
  },
  { _id: false }
);

/**
 * Question Model
 * Pre-created questions before the event.
 */
const questionSchema = new Schema(
  {
    Question: {
      type: String,
      required: true,
    },
    QuestionAssets: [
      {
        type: String, // image / audio URLs
      },
    ],
    // Normalized (lowercase + trimmed) expected answers.
    answer: [
      {
        type: String,
        required: true,
        trim: true,
        lowercase: true,
      },
    ],
    // Clue or instructions for the next location step
    nextLocationHint: {
      type: String,
      default: null,
    },
    // Verification code found at the physical/Gather location.
    // Plaintext string/number generated by backend and returned to student when previous clue is solved.
    verificationCode: {
      type: String,
      default: null,
      trim: true,
    },
    hints: {
      type: hintSchema,
      default: null,
    },
    isFirstPuzzle: {
      type: Boolean,
      default: false,
    },
    isFinalPuzzle: {
      type: Boolean,
      default: false,
    },
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

module.exports = mongoose.model('Question', questionSchema);
