const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const { Schema } = mongoose;

const STUDENT_STATUS = ['active', 'inactive'];

const studentSchema = new Schema(
  {
    // Sequential number generated by Counter: 100001, 100002, …
    userNumber: {
      type: Number,
      required: true,
      unique: true,
      index: true,
    },

    // Auto-generated from userNumber: "user100001" or instagram style "rahul_sharma"
    username: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },

    name: {
      type: String,
      required: true,
      trim: true,
    },

    email: {
      type: String,
      trim: true,
      lowercase: true,
      default: null,
    },

    password: {
      type: String,
      required: true,
      select: false, // never returned by default in queries
    },

    role: {
      type: String,
      enum: ['STUDENT'],
      default: 'STUDENT',
    },

    status: {
      type: String,
      enum: STUDENT_STATUS,
      default: 'active',
    },

    // Assigned WorkAdventure map (1 of 5 routes)
    mapId: {
      type: Schema.Types.ObjectId,
      ref: 'Map',
      default: null,
      index: true,
    },

    // Assigned question sequence set
    setsKey: {
      type: Schema.Types.ObjectId,
      ref: 'Sets',
      default: null,
      index: true,
    },

    // Unique personal Main Gate victory verification code (e.g. "GATE-7391" or "7391")
    mainGateCode: {
      type: String,
      default: null,
      index: true,
    },

    // Game progress fields
    gameStatus: {
      type: String,
      enum: ['not_started', 'in_progress', 'completed'],
      default: 'not_started',
      index: true,
    },
    startedAt: { type: Date, default: null },
    completedAt: { type: Date, default: null },
    currentQuestionId: {
      type: Schema.Types.ObjectId,
      ref: 'Question',
      default: null,
    },
    totalHintPenaltySeconds: { type: Number, default: 0 },
    finalAnswerSolvedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// Password hashing helper
studentSchema.statics.hashPassword = async function (plainPassword) {
  const salt = await bcrypt.genSalt(10);
  return bcrypt.hash(plainPassword, salt);
};

studentSchema.methods.comparePassword = function (plainPassword) {
  return bcrypt.compare(plainPassword, this.password);
};

module.exports = mongoose.model('Student', studentSchema);
module.exports.STUDENT_STATUS = STUDENT_STATUS;
