const mongoose = require('mongoose');
const bcrypt = require('bcrypt');
const { Schema } = mongoose;

const STUDENT_STATUS = ['active', 'inactive'];

const studentSchema = new Schema(
  {
    // Sequential number generated by Counter: 100001, 100002, …
    userNumber: {
      type: Number,
      required: true,
      unique: true,
      index: true,
    },

    // Auto-generated from userNumber: "user100001"
    username: {
      type: String,
      required: true,
      unique: true,
      lowercase: true,
      trim: true,
      index: true,
    },

    name: {
      type: String,
      required: true,
      trim: true,
    },

    email: {
      type: String,
      trim: true,
      lowercase: true,
      default: null,
    },

    passwordHash: {
      type: String,
      required: true,
      select: false, // never returned by default in queries
    },

    role: {
      type: String,
      enum: ['STUDENT'],
      default: 'STUDENT',
    },

    status: {
      type: String,
      enum: STUDENT_STATUS,
      default: 'active',
    },

    // Assigned map
    mapId: {
      type: Schema.Types.ObjectId,
      ref: 'Map',
      default: null,
    },

    // Unique route key for this student (e.g. "ROUTE_A_K92M")
    routeKey: {
      type: String,
      unique: true,
      sparse: true,  // allows multiple null values during creation
      uppercase: true,
      trim: true,
      index: true,
    },

    // Unique personal Main Gate victory verification code (e.g. "GATE-7391")
    mainGateCode: {
      type: String,
      unique: true,
      sparse: true,
      uppercase: true,
      trim: true,
      index: true,
    },

    lastLogin: {
      type: Date,
      default: null,
    },

    // Game progress fields (mirrors old Team fields)
    gameStatus: {
      type: String,
      enum: ['not_started', 'in_progress', 'completed'],
      default: 'not_started',
    },
    startedAt: { type: Date, default: null },
    completedAt: { type: Date, default: null },
    currentStageIndex: { type: Number, default: 0 },
    currentQuestionId: {
      type: Schema.Types.ObjectId,
      ref: 'Question',
      default: null,
    },
    totalHintPenaltySeconds: { type: Number, default: 0 },
    totalBonusRewardSeconds: { type: Number, default: 0 },
    finalAnswerSolvedAt: { type: Date, default: null },
  },
  { timestamps: true }
);

// ---- Password helpers ----

studentSchema.statics.hashPassword = async function (plainPassword) {
  const salt = await bcrypt.genSalt(12);
  return bcrypt.hash(plainPassword, salt);
};

studentSchema.methods.comparePassword = function (plainPassword) {
  return bcrypt.compare(plainPassword, this.passwordHash);
};

module.exports = mongoose.model('Student', studentSchema);
module.exports.STUDENT_STATUS = STUDENT_STATUS;
